image: node

variables:
  NAME: 'devrecipe-web'

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm test

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u mabotn -p $DOCKER_REGISTRY_SECRET registry.gitlab.com
    - docker build -t registry.gitlab.com/devrecipe/$NAME:latest -t registry.gitlab.com/devrecipe/$NAME:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/devrecipe/$NAME

production:
  stage: deploy
  environment:
    name: production
    url: https://www.devrecipe.com
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh ubuntu@k8s.devrecipe.com "sudo deploy production $NAME $CI_COMMIT_SHA devrecipe.com"
